### ISSUE TITLE
Explicitly specify supported libmpv-dev version

### ISSUE THREAD

**Issue by dreamer-dead** [flaviotordini/media#1]
As of now it is possible to build this library with libmpv-dev version 0.29.0
This version is in the Cosmic repos (https://packages.ubuntu.com/cosmic/libmpv-dev) by default, but not in older distros.
It would be great to say what version exactly I need to compile minitube for example.

**Comment by flaviotordini** [comment]
Yes 0.29.0 is required. Added to the README.
